### ISSUE TITLE
Microdata Does not parse content="" on item property fields

### ISSUE THREAD

**Issue by rbairwell** [jkphl/micrometa#13]
Problem
====
According to http://schema.org/Review and https://search.google.com/structured-data/testing-tool/u/0/ , the following schema:
```
<div itemscope itemtype="http://schema.org/Offer">
    <!--price is 1000, a number, with locale-specific thousands separator
    and decimal mark, and the $ character is marked up with the
    machine-readable code "USD" -->
    <span itemprop="priceCurrency" content="USD">$</span><span
        itemprop="price" content="1000.00">1,000.00</span>
    <link itemprop="availability" href="http://schema.org/InStock" />In stock
</div>
```
is valid and "priceCurrency" should have the value of "USD" (and price should have "1000.00").

**Comment by rbairwell** [comment]
>  Even if HTML Microdata has never been finally specced and may be considered "dead" (no active maintenance since 2013), the [value retrieval algorithm](https://www.w3.org/TR/microdata/#values) does consider the content attribute only for <meta> elements. It seems to me that content is neither part of the [Microdata syntax](https://www.w3.org/TR/microdata/#the-basic-syntax) nor a native attribute for <span>.

I would agree with you here (and thanks for posting the W3C spec : I've been working on this project for about a week now and it never occurred to me to check there!). The spec does seem dead and that the "content" attribute isn't listed.

> However, I'm not really sure what is correct in this case.

This is the problem I've encountered. Schema.org is [littered](http://schema.org/Review) with different examples* which show the content attribute being "misused" (in fact, the [Offer](http://schema.org/Offer) spec specifically states: ```Note that both RDFa and Microdata syntax allow the use of a "content=" attribute for publishing simple machine-readable values alongside more human-friendly formatting.```).

I've been working on the assumption that if Schema.org says something and the [Google validator](https://search.google.com/structured-data/testing-tool/u/0/)  agrees, then the system should be accepting of that value as well (yes, I know Google is one of the four sponsors of Schema.org so perhaps not a good case of "independent validation").

I think that if web browsers need to cope with reasonably invalid HTML, the microdata parser should do its best to cope as well.
* = Schema.org is also littered with numerous invalid examples according to their own spec (date formats, superseded tags etc), so perhaps it's not to be fully trusted...

**Comment by jkphl** [comment]
Agreed in all points (especially that Google is everything but neutral — here and elsewhere ;) ). I'll merge your fix, although Google is misusing the `content` attribute IMHO. I also doubt that RDFa allows the `content` attribute (at least in arbitrary situations), but I might be corrected.

This is also potentially relevant for my [rdfa-lite-microdata](https://github.com/jkphl/rdfa-lite-microdata) module and the [next generation of micrometa](https://github.com/jkphl/micrometa/tree/v2) which I'm working on this very minute. You might expect a first release within the next 2 weeks I'd say.

Again, thanks for your contribution!
