### ISSUE TITLE
Example from documentation is not working

### ISSUE THREAD

**Issue by iamntz** [jkphl/micrometa#19]
Hey guys, I tried to follow documentation and I failed to get a working example without having to take a look at the demo file.

So, here is how it is into documentation:

```
use Jkphl\Micrometa\Ports\Parser;
$micrometa = new Parser();
$items = $micrometa('http://example.com');
```

This will fail, since `Parser` class is nowhere to find.

**Comment by iamntz** [comment]
Actually this is not true. The problem resides in the `composer require jkphl/micrometa` instructions, since it will install 1.0, not 2.x 👍

**Comment by jkphl** [comment]
@iamntz Glad you could figure it out! ;)
