### ISSUE TITLE
Uncaught exception 'Jkphl\Domfactory\Ports\RuntimeException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by yourchoice** [jkphl/micrometa#23]
Hi,

I have this error:
Uncaught exception 'Jkphl\Domfactory\Ports\RuntimeException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate in lib\vendor\jkphl\dom-factory\src\Domfactory\Infrastructure\Dom.php:72

Any idea? Exists the posibility to can set something like $client->setOption(CURLOPT_CAINFO, $certKeysPath.'/cacert.pem'); ??

**Comment by yourchoice** [comment]
I think I found in options posibility to set 'cert':

$options = [
    'client' => ['timeout' => 30],
    'request' => ['verify' => false],
    'cert' => ['../cert/cacert.pem', ''],
];

Thanks

**Comment by jkphl** [comment]
This looks like what I would've suggested. ;)
