### ISSUE TITLE
Porque?  

### ISSUE THREAD

**Issue by brayanirving** [jkphl/micrometa#28]
https://github.com/jkphl/micrometa/blob/21058a98a4ebcd596786de99b3c3fac282498170/src/Micrometa/Infrastructure/Parser/JsonLD.php#L121

**Comment by jkphl** [comment]
@brayanirving First of all, thanks for your support! Could you please provide a more descriptive version of your issue, including an example (e.g. JSON-LD snippet) that doesn't work as you expect? As you might imagine, the code didn't write itself, so even if I don't remember the exact reason for that very line of code I still probably had one at that time, and it probably even made sense in that particular situation. So thanks for being a bit more verbose.

**Comment by brayanirving** [comment]
Hello, this line "break" prevents the code from scratching all the ld+json of the documents. I removed it, and managed to extract all the ld+json parts.
