### ISSUE TITLE
Microformats on some websites are not detected

### ISSUE THREAD

**Issue by zergu** [jkphl/micrometa#3]
Any ideas why microfromats are not detected on this website?
http://gotowanie.onet.pl/przepisy/krewetki-z-grilla,107423.html

Google testing tools can detect recipe there.

**Comment by jkphl** [comment]
Hey @zergu,

thanks for reporting this. I'll look into it as soon as possible.

Cheers, Joschi

**Comment by jkphl** [comment]
I obviously needed to fix my definition of "top-level item" for your recipies to show up. Should work as of [v0.3.3](https://github.com/jkphl/micrometa/releases/tag/v0.3.3)!
