### ISSUE TITLE
ML\JsonLD\Exception\JsonLdException: Loading https://schema.org failed

### ISSUE THREAD

**Issue by jslim89** [jkphl/micrometa#34]
I was trying to parse the data from this link

https://www.lazada.co.id/products/dispenser-mini-air-minum-anak-aneka-karakter-hello-kitty-helo-kity-hk-doraemon-doremon-i363397334-s382716523.html

But then it throws `JsonLdException`.

When I try in [Google schema tool](https://search.google.com/structured-data/testing-tool), it works fine.

![google-schema](https://user-images.githubusercontent.com/797182/55449897-fe1f5b00-55ff-11e9-8e97-889b6b728ab3.png)

This is my setup

```php
$options = [ 
    'client'  => [
        'timeout' => 30, 
        'curl' => [
            CURLOPT_PROXY => 'proxy-host',
            CURLOPT_PROXYUSERPWD => 'proxy-pass',
        ],  
    ],  
    'request' => [
        'verify'  => false,
        'headers' => [
            'Cache-Control' => 'no-cache, no-store, must-revalidate',
            'Pragma'        => 'no-cache',
            'User-Agent'    => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
            'Expires'       => 'Thu, 19 Nov 1981 08:52:00 GMT',
        ]   
    ],  
];

$micrometa = new Parser();
$micrometa($url, null, FORMAT::ALL, $options);
```

Anything I've missing out?

**Comment by greggh** [comment]
My code was working and now isn't. The same thing is happening to me. Maybe a change at schema.org?

**Comment by greggh** [comment]
A schema.org maintainer responded over in the thread I referenced.  It was a problem that they fixed on April 5th (a few days ago.) They believe it is fixed now.

**Comment by greggh** [comment]
Hey @jslim89 we got this fixed over in the other thread, it should be working for you now.

**Comment by jslim89** [comment]
@greggh Thanks for the comment. I was unable to figure out the problem, eventually I switched to use [extruct](https://github.com/scrapinghub/extruct).

**Comment by jkphl** [comment]
Sorry for the silence, guys, and thanks @greggh for figuring it out!
