### ISSUE TITLE
JSONLD parsing failed; array was returned where itemtype was expected

### ISSUE THREAD

**Issue by rvanlaak** [jkphl/micrometa#43]
Parsing fails on `JSONLD::parseNodeType`:

> Call to a member function getId() on array

Happens on parsing the following URL:

https://www.thelocal.es/20190227/why-is-veganism-on-the-rise-among-young-people-in-spain

**Comment by rvanlaak** [comment]
We tested a fix by trying to always return the first result in case an array was detected, but that seems to have side effects.

@jkphl any idea what would be going on here?

**Comment by Sarke** [comment]
I made this modification for now, since I don't really care about multiple types on this.

```php
protected function parseNodeType(NodeInterface $node)
{
	/** @var Node $itemType */
	$itemType = $node->getType();
	if (is_array($itemType))
		$itemType = reset($itemType);

	return $itemType ? [$this->vocabularyCache->expandIRI($itemType->getId())] : [];
}
```

**Comment by rvanlaak** [comment]
We tried something similar, but had the idea it had a regression. Could you create a PR to see if all tests would pass?

**Comment by rvanlaak** [comment]
@Sarke thank you for your snippet! 

It made me think about what could go wrong, and after some more debugging we found out that the `parseNodeType` does not properly handle all `itemType->getType` return options, which also can be `null`, or can return an array with `NodeInterfaces`.

We had over 5,000 events in Sentry already. PR #46 fixes that.

**Comment by Sarke** [comment]
Thanks @rvanlaak!

As for the Yoast SEO issue, I used the snippet in combination with the `JsonLDFilteredParser` you posted in the other issue: https://github.com/jkphl/micrometa/issues/16#issuecomment-550226719

**Comment by rvanlaak** [comment]
For clarification; it's not a problem caused by the Yoast plugin, as it is perfectly fine to have more than one `@type`

```js
"@type": [
    "Person",
    "Organization"
 ],
```
