### ISSUE TITLE
JSON-LD support?

### ISSUE THREAD

**Issue by 4rn0** [jkphl/micrometa#6]
Any chance on adding JSON-LD support? :-)

**Comment by jkphl** [comment]
@4rn0 That's something I was already thinking about myself! I'll see what I can do — the only limiting factor is my (aweful) time budget. ;) I'm planning to spend some days on my OS projects around christmas, maybe I'll find some time to add JSON-LD support. I'll keep you posted!

**Comment by jkphl** [comment]
@jkphl Note to self: Maybe check out https://github.com/digitalbazaar/php-json-ld as alternative parser or directly use the compacted JSON for creating items?

**Comment by jkphl** [comment]
@4rn0 I'm happy to announce that *micrometa* supports JSON-LD extraction as of [v1.0.0](https://github.com/jkphl/micrometa/releases/tag/v1.0.0)! Please let me know what you think.

**Comment by 4rn0** [comment]
Did a quick test and it seems to be working great! Thanks! :-)
