### ISSUE TITLE
Add tests for Microdata and JSON-LD

### ISSUE THREAD

**Issue by jkphl** [jkphl/micrometa#7]
... and use Travis CI for automatic builds

**Comment by cweiske** [comment]
Consider relying on the official microformats test suite: https://github.com/microformats/tests

**Comment by jkphl** [comment]
@cweiske After having had a look at the official mf2 test suite I wonder if it's really important for *micrometa* to use it as as base for its tests. As *micrometa* is delegating all mf2 parsing to [php-mf2](https://github.com/indieweb/php-mf2) and "just" aggregating the results with other micro information format parsers (HTML Microdata and JSON-LD), I'd consider it more important that *php-mf2* itself sticked to that test suite (which it doesn't, at least not in its current form). For *micrometa* I'd consider it more important to ensure the proper mapping between e.g. *php-mf2*'s output and *micrometa*'s own unified way to represent items (although it's of course still tempting to use the official test suite in some way as one should think it's kept up to date). What do you think?

**Comment by cweiske** [comment]
oh, I had not realized that micrometa actually uses php-mf2. I had hoped to find a library not dependent on that :/

But yes, you're totally right.

**Comment by jkphl** [comment]
@cweiske Any reason you want to avoid php-mf2?

**Comment by cweiske** [comment]
All PHP implementations rely on that single lib. I don't think that's good.

**Comment by jkphl** [comment]
@cweiske But on the other hand it might not be super effective to have several PHP implementations in parallel but instead focus on one that can serve as a reference and then have implementations in multiple  other languages than PHP. No?

**Comment by cweiske** [comment]
Diversity has served evolution on earth well, so I think it does so for computers, too :)

**Comment by jkphl** [comment]
@cweiske FYI: I just pushed out the next major release with support for additional formats & tests.
